name: Build & Deploy GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dateProgramHTML
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖并打包
        run: |
          npm install --ignore-scripts
          npx vite build

      - name: 上传打包产物dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dateProgramHTML/dist

  deploy-pages:
    needs: build-site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: 部署页面
        id: deploy
        uses: actions/deploy-pages@v4
